name: Release (Publish + Docs)

on:
  push:
    tags:
      - '*'

# GITHUB_TOKEN needs write access to releases and gh-pages
permissions:
  contents: write

jobs:
  publish-docs:
    name: publish-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PSPDEV Environment
        run: |
          URL="https://github.com/pspdev/pspdev/releases/download/v20240609/pspdev-ubuntu-latest-x86_64.tar.gz"
          FILE=$(basename "$URL")
          wget "$URL"
          tar -xzf "$FILE"
          echo "PSPDEV=$PWD/pspdev" >> "$GITHUB_ENV"
          echo "$PWD/pspdev/bin" >> "$GITHUB_PATH"

      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate documentation
        run: make gendoc

      - name: Publish to GitHub Pages
        run: make ghpages
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PSPDEV Environment
        run: |
          URL="https://github.com/pspdev/pspdev/releases/download/v20240609/pspdev-ubuntu-latest-x86_64.tar.gz"
          FILE=$(basename "$URL")
          wget "$URL"
          tar -xzf "$FILE"
          echo "PSPDEV=$PWD/pspdev" >> "$GITHUB_ENV"
          echo "$PWD/pspdev/bin" >> "$GITHUB_PATH"

      - name: Build project
        run: make

      - name: Generate release files
        run: make release

      - name: Compress release
        run: |
          mkdir -p dist
          tar -czf dist/oslib-release-${GITHUB_REF##*/}.tar.gz Distrib/

      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate documentation
        run: make gendoc

      - name: Publish to GitHub Pages
        run: make ghpages
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release on GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/oslib-release-${GITHUB_REF##*/}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
